WITH
    Q1  AS
    (
        SELECT
                ACCOUNT_ID
            ,   SUM(CASE WHEN TRANSACTION_CODE IN ('STAKE') THEN ABS(AMOUNT) ELSE 0 END) STAKE_AMT
            ,   SUM(CASE WHEN TRANSACTION_CODE IN ('DEPOSIT','FINANCE_CORRECTION_DEPOSIT') THEN AMOUNT ELSE 0 END) DEPOSIT_AMT
            ,   SUM(CASE WHEN TRANSACTION_CODE IN ('WITHDRAWAL_COMPLETED','FINANCE_CORRECTION_WITHDRAWAL') THEN AMOUNT ELSE 0 END) WITHDRAWAL_AMT
            ,   SUM(CASE WHEN TRANSACTION_CODE IN ('DEPOSIT','FINANCE_CORRECTION_DEPOSIT') THEN AMOUNT ELSE 0 END)*.1 DEPOSIT_VARIANCE_1
            ,   SUM(CASE WHEN TRANSACTION_CODE IN ('DEPOSIT','FINANCE_CORRECTION_DEPOSIT') THEN AMOUNT ELSE 0 END)-SUM(CASE WHEN TRANSACTION_CODE IN ('DEPOSIT','FINANCE_CORRECTION_DEPOSIT') THEN AMOUNT ELSE 0 END)*.1 BELOW
            ,   SUM(CASE WHEN TRANSACTION_CODE IN ('DEPOSIT','FINANCE_CORRECTION_DEPOSIT') THEN AMOUNT ELSE 0 END)+SUM(CASE WHEN TRANSACTION_CODE IN ('DEPOSIT','FINANCE_CORRECTION_DEPOSIT') THEN AMOUNT ELSE 0 END)*.1 ABOVE
        FROM
            PROD_CLEAN.SPORTSBOOK.ACCOUNT_STATEMENTS
        WHERE
                BRAND_CODE != 'HRD_RETAIL'
            AND ACCOUNT_ID IN (SELECT ACCOUNT_ID FROM PROD_CLEAN.SPORTSBOOK.ACCOUNTS WHERE TEST = 0)
            -- AND TRANSACTION_CODE IN ('DEPOSIT','WITHDRAWAL_PENDING','STAKE')
            AND MONTH(HRD_UTILITIES.PUBLIC.EST_TIME(TRANSACTION_TIMESTAMP)) >= MONTH(DATEADD(MONTH,-1,CURRENT_TIMESTAMP))
        GROUP BY
            ACCOUNT_ID
        HAVING
                DEPOSIT_AMT > 4999
            AND WITHDRAWAL_AMT BETWEEN BELOW AND ABOVE
            AND ABS(STAKE_AMT) < ABS(DEPOSIT_VARIANCE_1)
    )
SELECT * FROM Q1